// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workspace_Management_System.Data;

#nullable disable

namespace Workspace_Management_System.Migrations
{
    [DbContext(typeof(WorkSpaceSysContext))]
    [Migration("20260122164303_ConfigureAspNetIdentit")]
    partial class ConfigureAspNetIdentit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Workspace_Management_System.Entities.TbBooking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CountOfPeople")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("RoomID");

                    b.Property<decimal>("RoomPrice")
                        .HasColumnType("money");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("StatusID");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__TbBookin__3214EC2799C40E10");

                    b.HasIndex("RoomId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("TbBooking", (string)null);
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbBookingProduct", b =>
                {
                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BookingID");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProductID");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductTotalPrice")
                        .HasColumnType("money");

                    b.Property<decimal>("ProductUnitPrice")
                        .HasColumnType("money");

                    b.HasKey("BookingId", "ProductId")
                        .HasName("PK_BookingProduct");

                    b.HasIndex("ProductId");

                    b.ToTable("TbBookingProduct", (string)null);
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbInvoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("money");

                    b.Property<DateTime>("InvoiceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("StatusID");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("money");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("TotalAfterDiscount")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalProductPrice")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalRoomPrice")
                        .HasColumnType("money");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdtedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__TbInvoic__3214EC27D3A57BB5");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "InvoiceNumber" }, "UQ__TbInvoic__D776E9819EF522B8")
                        .IsUnique();

                    b.ToTable("TbInvoice", (string)null);
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbInvoiceBooking", b =>
                {
                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("InvoiceID");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("BookingID");

                    b.Property<decimal>("BookingProductPrice")
                        .HasColumnType("money");

                    b.Property<decimal>("BookingRoomPrice")
                        .HasColumnType("money");

                    b.Property<decimal>("BookingTotal")
                        .HasColumnType("money");

                    b.HasKey("InvoiceId", "BookingId")
                        .HasName("PK_InvoiceBooking");

                    b.HasIndex(new[] { "BookingId" }, "UQ_InvoiceBooking_BookingID")
                        .IsUnique();

                    b.ToTable("TbInvoiceBooking", (string)null);
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbMedium", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("RelativePathFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("RoomID");

                    b.HasKey("Id")
                        .HasName("PK__TbMedia__3214EC27B5D05E32");

                    b.HasIndex("RoomId");

                    b.ToTable("TbMedia");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbPricingType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__TbPricin__3214EC2759277269");

                    b.ToTable("TbPricingType", (string)null);
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TbProduc__3214EC27DF8CC838");

                    b.ToTable("TbProduct", (string)null);
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<long>("PricingTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("PricingTypeID");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__TbRoom__3214EC2719D04C6E");

                    b.HasIndex("PricingTypeId");

                    b.ToTable("TbRoom", (string)null);
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__TbSettin__3214EC270CDDF9CE");

                    b.HasIndex(new[] { "KeyName" }, "UQ__TbSettin__F0A2A337878EAF24")
                        .IsUnique();

                    b.ToTable("TbSetting", (string)null);
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StatusTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("StatusTypeID");

                    b.HasKey("Id")
                        .HasName("PK__TbStatus__3214EC276FA2DC0B");

                    b.HasIndex("StatusTypeId");

                    b.ToTable("TbStatus", (string)null);
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbStatusType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__TbStatus__3214EC2728004003");

                    b.ToTable("TbStatusType", (string)null);
                });

            modelBuilder.Entity("Workspace_Managment_System.identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbBooking", b =>
                {
                    b.HasOne("Workspace_Management_System.Entities.TbRoom", "Room")
                        .WithMany("TbBookings")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Room");

                    b.HasOne("Workspace_Management_System.Entities.TbStatus", "Status")
                        .WithMany("TbBookings")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Status");

                    b.HasOne("Workspace_Managment_System.identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbBookingProduct", b =>
                {
                    b.HasOne("Workspace_Management_System.Entities.TbBooking", "Booking")
                        .WithMany("TbBookingProducts")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingProduct_Booking");

                    b.HasOne("Workspace_Management_System.Entities.TbProduct", "Product")
                        .WithMany("TbBookingProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_BookingProduct_Product");

                    b.Navigation("Booking");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbInvoice", b =>
                {
                    b.HasOne("Workspace_Management_System.Entities.TbStatus", "Status")
                        .WithMany("TbInvoices")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoice_Status");

                    b.HasOne("Workspace_Managment_System.identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbInvoiceBooking", b =>
                {
                    b.HasOne("Workspace_Management_System.Entities.TbBooking", "Booking")
                        .WithOne("TbInvoiceBooking")
                        .HasForeignKey("Workspace_Management_System.Entities.TbInvoiceBooking", "BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceBooking_Booking");

                    b.HasOne("Workspace_Management_System.Entities.TbInvoice", "Invoice")
                        .WithMany("TbInvoiceBookings")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceBooking_Invoice");

                    b.Navigation("Booking");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbMedium", b =>
                {
                    b.HasOne("Workspace_Management_System.Entities.TbRoom", "Room")
                        .WithMany("TbMedia")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_Media_Room");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbRoom", b =>
                {
                    b.HasOne("Workspace_Management_System.Entities.TbPricingType", "PricingType")
                        .WithMany("TbRooms")
                        .HasForeignKey("PricingTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Room_PricingType");

                    b.Navigation("PricingType");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbStatus", b =>
                {
                    b.HasOne("Workspace_Management_System.Entities.TbStatusType", "StatusType")
                        .WithMany("TbStatuses")
                        .HasForeignKey("StatusTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Status_StatusType");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbBooking", b =>
                {
                    b.Navigation("TbBookingProducts");

                    b.Navigation("TbInvoiceBooking");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbInvoice", b =>
                {
                    b.Navigation("TbInvoiceBookings");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbPricingType", b =>
                {
                    b.Navigation("TbRooms");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbProduct", b =>
                {
                    b.Navigation("TbBookingProducts");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbRoom", b =>
                {
                    b.Navigation("TbBookings");

                    b.Navigation("TbMedia");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbStatus", b =>
                {
                    b.Navigation("TbBookings");

                    b.Navigation("TbInvoices");
                });

            modelBuilder.Entity("Workspace_Management_System.Entities.TbStatusType", b =>
                {
                    b.Navigation("TbStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
